const mangaList = [
    {
        id: 1,
        url: "miracle-hero",
        title: "Miracle Hero!",
        img: "https://reaperscans.com/wp-content/uploads/2021/11/XL.jpg.webp",
        type: "comic",
        category: "Manhwa",
        rating: 3.2,
        reviews: 1999,
    },
    {
        id: 2,
        url: "the-constellation-that-returned-from-hell",
        title: "The Constellation That Returned From Hell",
        img: "https://reaperscans.com/wp-content/uploads/2021/10/returnfromhell.jpg.webp",
        type: "comic",
        category: "Manhwa",
        rating: 4.5,
        reviews: 1999,
    },
    {
        id: "94-123ad-4123a",
        url: "the-return-of-the-disaster-class-hero",
        title: "The Return of The Disaster-Class Hero",
        img: "https://reaperscans.com/wp-content/uploads/2021/10/RDCH_Cover.jpg.webp",
        type: "comic",
        category: "Manhwa",
        rating: 3.7,
        reviews: 1999,
        tags: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
        description: `Raven Valt, the second son of a lowly nobleman, had been branded as a traitor. With the promise of a pardon, he was sent to fight monsters with the worst unit in the world, the “Rakshasa” Corps.

Raven survived ten years in a place where most only lasted one. One day before his pardon, he was on his final mission on the battlefield alongside Eren Pendragon, heir to the Pendragon Duchy… when everything crumbled before his very eyes.`,
    },
    {
        id: 4,
        url: "estio",
        title: "Estio",
        img: "https://reaperscans.com/wp-content/uploads/2021/12/resource-1.jpg.webp",
        type: "comic",
        category: "Manhwa",
        rating: 4.5,
        reviews: 1999,
    },
    {
        id: 5,
        url: "regressor-instruction-manual",
        title: "Regressor Instruction Manual",
        img: "https://reaperscans.com/wp-content/uploads/2021/10/RIM-COVER-2.jpg.webp",
        type: "comic",
        category: "Manhwa",
        rating: 4.5,
        reviews: 1999,
    },
    {
        id: 6,
        url: "record-of-the-mightiest-lord",
        title: "Record of The Mightiest Lord",
        img: "https://reaperscans.com/wp-content/uploads/2021/10/ROML.jpg.webp",
        type: "comic",
        category: "Manhua",
        rating: 4.5,
        reviews: 1999,
    },
    {
        id: 7,
        url: "arcane-sniper",
        title: "Arcane Sniper",
        img: "https://reaperscans.com/wp-content/uploads/2021/07/ASNIP-1.jpg.webp",
        type: "comic",
        category: "Webtoon",
        rating: 4.5,
        reviews: 1999,
    },
    {
        id: 8,
        url: "seoul-station-necromancer",
        title: "Seoul Station Necromancer",
        img: "https://reaperscans.com/wp-content/uploads/2021/10/cover.jpg.webp",
        type: "comic",
        category: "Comic",
        rating: 4.5,
        reviews: 1999,
    },
    {
        id: 9,
        url: "estio",
        title: "Estio",
        img: "https://reaperscans.com/wp-content/uploads/2021/12/resource-1.jpg.webp",
        type: "comic",
        category: "Manhua",
        rating: 4.5,
        reviews: 1999,
    },
    {
        id: 10,
        url: "regressor-instruction-manual",
        title: "Regressor Instruction Manual",
        img: "https://reaperscans.com/wp-content/uploads/2021/10/RIM-COVER-2.jpg.webp",
        type: "comic",
        category: "Comic",
        rating: 4.5,
        reviews: 1999,
    },
    {
        id: 11,
        url: "estio",
        title: "Estio",
        img: "https://reaperscans.com/wp-content/uploads/2021/12/resource-1.jpg.webp",
        type: "comic",
        category: "Manhua",
        rating: 4.5,
        reviews: 1999,
    },
    {
        id: 12,
        url: "regressor-instruction-manual",
        title: "Regressor Instruction Manual",
        img: "https://reaperscans.com/wp-content/uploads/2021/10/RIM-COVER-2.jpg.webp",
        type: "comic",
        category: "Manhua",
        rating: 4.5,
        reviews: 1999,
    },
];

const latestChapters = [
    {
        id: 1,
        url: "miracle-hero",
        title: "Miracle Hero!",
        chapter: 10,
        time: new Date(),
        type: "comic",
    },
    {
        id: 2,
        url: "miracle-hero",
        title: "Miracle Hero!",
        chapter: 9,
        time: new Date(),
        type: "comic",
    },
    {
        id: 3,
        url: "miracle-hero",
        title: "Miracle Hero!",
        chapter: 8,
        time: new Date(),
        type: "comic",
    },
    {
        id: 4,
        url: "miracle-hero",
        title: "Miracle Hero!",
        chapter: 7,
        time: new Date(),
        type: "comic",
    },
    {
        id: 5,
        url: "miracle-hero",
        title: "Miracle Hero!",
        chapter: 6,
        time: new Date(),
        type: "comic",
    },
    {
        id: 6,
        url: "miracle-hero",
        title: "Miracle Hero!",
        chapter: 5,
        time: new Date(),
        type: "comic",
    },
    {
        id: 7,
        url: "miracle-hero",
        title: "Miracle Hero!",
        chapter: 4,
        time: new Date(),
        type: "comic",
    },
    {
        id: 8,
        url: "miracle-hero",
        title: "Miracle Hero!",
        chapter: 3,
        time: new Date(),
        type: "comic",
    },
    {
        id: 9,
        url: "miracle-hero",
        title: "Miracle Hero!",
        chapter: 2,
        time: new Date(),
        type: "comic",
    },
    {
        id: 10,
        url: "miracle-hero",
        title: "Miracle Hero!",
        chapter: 1,
        time: new Date(),
        type: "comic",
    },
];

const tags = [
    {
        label: "Hành động",
        value: "action",
    },
    {
        label: "Phiêu lưu",
        value: "adventure",
    },
    {
        label: "Chuyển sinh",
        value: "isekai",
    },
    {
        label: "Lãng mạn",
        value: "romance",
    },
    {
        label: "One-shot",
        value: "one-shot",
    },
    {
        label: "Hài hước",
        value: "comedy",
    },
    {
        label: "Bi kịch",
        value: "tragedy",
    },
    {
        label: "Kinh dị",
        value: "horror",
    },
];

export { mangaList, latestChapters, tags };
